### ISSUE TITLE
Missing Password parameter in Set-LabVMDefaults function

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lab#10]
Set-LabVMDefaults -Password 'Some3P@ssw0rdString'
Set-LabVMDefaults : A parameter cannot be found that matches parameter name 'Password'.
At line:1 char:19
+ Set-LabVMDefaults -Password 'Some3P@ssw0rdString'
+                   ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-LabVMDefaults], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-LabVMDefaults

**Comment by iainbrighton** [comment]
Thanks! I was aware that this parameter was missing, but also conscious that we really need to implement a SecureString or the equivalent.

When this module eventually gets pushed to the gallery, anything with a -Password or -Credential parameter that is using a String will get rejected. Do you have any thoughts on how you would like to see this implemented?

In the interim, I'm happy to review the pull request and merge :)

**Comment by csandfeld** [comment]
Thanks Iain.

Don't really have any thoughts on that at this point to be honest. Just needed it to work for some testing I started today. Will see if I can come of with a clever idea, but don't have much experience in that area at this point (in other words, don't hold your breath).

**Comment by iainbrighton** [comment]
OK - no worries - thanks for giving it a spin! I'll merge the pull request when I get a chance; just be aware that there may be a breaking change in the near future.

If you have any other suggestions or problems, just log an issue/enhancement :D
