### ISSUE TITLE
Hyper-V PowerShell module not installed on Windows Server 2016 Technical Preview 3

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lab#15]
When running Start-LabHostConfiguration on Windows Server 2016 Technical Preview 3, it does not install the needed Hyper-V PowerShell module, as that Windows Feature is no longer a Sub-feature of Hyper-V.

In 2016 TP3 it resides under:
[ ] Remote Server Administration Tools                  RSAT                           Available
	...
    [ ] Role Administration Tools                       RSAT-Role-Tools                Available
        ...
	    [ ] Hyper-V Management Tools                    RSAT-Hyper-V-Tools             Available
            [ ] Hyper-V GUI Management Tools            Hyper-V-Tools                  Available
            [ ] Hyper-V Module for Windows PowerShell   Hyper-V-PowerShell             Available
        ...

**Comment by iainbrighton** [comment]
Funny you should say that.. I did install on 2016 TP3 and now remember that I had this exact issue.

I did create a GutHub issue and when I finally got around to looking at it, the 'IncludeAllSubFeature' parameter was used. I couldn't recreate the issue on Win 8.1 or 2012 R2. I obviously forgot the fact that it was a 2016 TP3 machine - DOH!

On another note, I can't believe MS have renamed/moved the Windows feature! That won't cause too many issues with existing DSC configurations :|

**Comment by csandfeld** [comment]
My best guess is that they moved it to ensure that people don't turn a core server into a full server by mistake by adding the Hyper-V role with all subfeatures. But you're right, it is likely to cause a few issues with existing configs.

Thank you for the quick fix.
