### ISSUE TITLE
Running as another user

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lab#19]
Because the Hyper-V cmdlets require administrator access this is enforced in the module manifest when loaded. Depending on the security configuration, it is not uncommon to have an alternative admin account that can be used to run a PowerShell instance.

Unfortunately, the BITS cmdlets that are used to download ISO and hotfixes do not run under an alternate security context and error:
```powershell
Start-BitsTransfer : The operation being requested was not performed because the user has not logged on to the
network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
At C:\Users\iainb\OneDrive\PowerShell\Modules\virtualenginelab\Lib\Resource.ps1:163 char:9
+         Start-BitsTransfer @startBitsTransferParams -ErrorAction Stop ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Mana
   gement.NewBitsTransferCommand
```
I think there are 2 obvious solutions to this problem:

__Option 1: We remove the Administrator restriction from the module:__
1. We warn when the module is loaded if running without admin rights.
2. This will permit downloading of module resources under the logged on user account.
3. We add a check for admin rights on the cmdlets that require it with an explicit message.

__Option 2: We revert to using System.Net.WebClient:__
1. The module used to use the System.Net.WebClient class.
2. This was a __lot__ slower than BITS - this may have been due to buffer size differences though.
3. This was changed because BITS shows a progress bar (handy for 4GB+ downloads!)

I'm leaning towards option 2 as it will avoid any confusion between admin and non-admin functionality?

**Comment by BladeFireLight** [comment]
Just droping the Administrator requiremend from the module resuls in this error
```
Start-LabConfiguration -ConfigurationData G:\VirtualEngineLab\en-US\Example.psd1 -Path G:\TestLab\Configurations
This Resource requires to be run as an Administrator.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCResources\MSFT_WindowsOptionalFeature\MSFT_WindowsOptionalFeature.psm1:277 char:9
+         throw $LocalizedData.ElevationRequired
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (This Resource r... Administrator.:String) [], RuntimeException
    + FullyQualifiedErrorId : This Resource requires to be run as an Administrator.
```
The only way to run as a basic user would be to require a credential parameter for an administrator account and then start additional powershell sessions running as the admin when it's required.

I like BITS, I wonder if there is another option to have bits run as system.

**Comment by BladeFireLight** [comment]
I can verify that the underlying issue with runas other user for admin is inherent in bits
```
PS G:\temp> bitsadmin /create testjob

BITSADMIN version 3.0 [ 7.8.10240 ]
BITS administration utility.
(C) Copyright 2000-2006 Microsoft Corp.

BITSAdmin is deprecated and is not guaranteed to be available in future versions of Windows.
Administrative tools for the BITS service are now provided by BITS PowerShell cmdlets.

Created job {68B1C5E1-E682-4770-B678-24EA8B0AD69C}.
PS G:\temp> bitsadmin /addfile testjob http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.17050.WI
NBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO g:\temp\test.iso

BITSADMIN version 3.0 [ 7.8.10240 ]
BITS administration utility.
(C) Copyright 2000-2006 Microsoft Corp.

BITSAdmin is deprecated and is not guaranteed to be available in future versions of Windows.
Administrative tools for the BITS service are now provided by BITS PowerShell cmdlets.

Unable to add file to job - 0x800704dd
The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist.
```

**Comment by iainbrighton** [comment]
Dropping Admin rights will cause issues, but it would permit you to download the resources!

I think it will be less confusing all round if we implement Invoke-WebRequest rather than BITS. Running some cmdlets as a standard user and others under a different context will just lead to a load of questions!

**Comment by BladeFireLight** [comment]
Not looking good

WARNING: Unable to query CCM_ClientUtilities: Invalid namespace 
Resource download failed: http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.17050.WINBL
UE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO.
At G:\VirtualEngineLab\Lib\Resource.ps1:212 char:13
+             throw ($localized.ResourceDownloadFailedError -f $Uri);
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Resource downlo..._EN-US_DV9.ISO.:String) [], RuntimeException
    + FullyQualifiedErrorId : Resource download failed: http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4F 
   E-C7D698DAEB96/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO.

**Comment by BladeFireLight** [comment]
I think I traced it down to this
```
PS C:\WINDOWS\system32>             [System.UInt32] $contentLength = $webClient.ResponseHeaders['Content-Length'];
Cannot convert value "4542291968" to type "System.UInt32". Error: "Value was either too large or too small for 
a UInt32."
At line:1 char:13
+             [System.UInt32] $contentLength = $webClient.ResponseHeade ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
 

PS C:\WINDOWS\system32> $webClient.ResponseHeaders['Content-Length'];
4542291968

PS C:\WINDOWS\system32> "$([int32]::MinValue) to $([int32]::MaxValue)"
-2147483648 to 2147483647
```

**Comment by BladeFireLight** [comment]
Changed UInt32 to UInt64, and it basically hung for a a bit then error our wit the same Resource download Failed error. but running the commands in InvokeWebClientDownload directly worked to download

**Comment by BladeFireLight** [comment]
guess I spoke too soon, tried again with a clean PowerShell and it started downloading.

**Comment by BladeFireLight** [comment]
Bottom line, you need Uint64 for the download progress calculations

**Comment by iainbrighton** [comment]
I'm closing this one out. If you still have problems with the Proxy server authentication, we can open another issue.
