### ISSUE TITLE
Set-LabHostDefault throw error when pointing to directory that does not exist

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lab#22]
Is this a bug, or is it intended behaviour?

I was under the impression that Start-LabHostConfiguration would create the directories if they do not exist, and thus I expected to be able to set defaults to directories that have not yet been created.

However when I try to, Set-LabHostDefault throw an error:

```PowerShell
D:\TestLab\MasterVirtualHardDisks path 'D:\TestLab\MasterVirtualHardDisks' is invalid.
At C:\Program Files\WindowsPowerShell\Modules\VirtualEngineLab\Src\LabHostDefaults.ps1:60 char:6
+ ...             throw ($localized.InvalidPathError -f $resolvedPath, $PSB ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (D:\TestLab\Mast...ks' is invalid.:String) [], RuntimeExcept 
   ion
    + FullyQualifiedErrorId : D:\TestLab\MasterVirtualHardDisks path 'D:\TestLab\MasterVirtualHardDisks' is  
   invalid.
```

**Comment by iainbrighton** [comment]
I think you could classify this as a bug as you're correct in that Start-LabHostConfiguration will create the target folders if they don't exist! I will review the pull request and merge it in. Thanks!
