### ISSUE TITLE
Built-in resource mismatch

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lab#26]
Issue initially raised by @SimonWhalin:

* Host is running 2012R2
 * Host has WMF 4
* VMs are running 2016TP3
 * VMs have WMF 5
* Generated MOF files are using v1.0 of the built-in WindowsFeature resource
* 2016TP3 VMs have v1.1 of the WindowsFeature resource
* Applying configuration errors with version mismatch

**Comment by iainbrighton** [comment]
I think that if the host was installed with WMF 5, then the built-in resource will be updated too? This will need testing.

If so, the WMF version on the host will need to match the highest WMF version deployed in the VMs. We could add a custom data entry on the built in media that specifies the minimum required WMF version? For example in the 2016 media entries, require that WMF 5 is installed on the host. This obviously wouldn't work with custom VHDXs!

Interestingly, I have not seen this issue the other way around, e.g. MOFs generated on v5 (Win10 host) being applied to v4 VMs (2012R2). Looks like MOFs generated on newer WMF versions will apply to older resources! You would have thought it would be the other way around?!

**Comment by SimonWahlin** [comment]
I've just tested this. Installing WMF 5 did not help.
Part of the mof generated still looks like this:  

	instance of MSFT_RoleResource as $MSFT_RoleResource1ref
	{
	ResourceID = "[WindowsFeature]ADDomainServices";
	 IncludeAllSubFeature = True;
	 Ensure = "Present";
	 SourceInfo = "D:\\TestLab\\Scripts\\ModuleVersiontTests\\LabConfig.ps1::93::13::WindowsFeature";
	 Name = "AD-Domain-Services";
	 ModuleName = "PSDesiredStateConfiguration";
	
	ModuleVersion = "1.0";
	
	DependsOn = {
	
	    "[xComputer]Server2016TP3"};
	
	 ConfigurationName = "LabConfig";
	
	};

The error I get in BootStrap.log on my VM states:  

	The PowerShell DSC resource MSFT_RoleResource from module <PSDesiredStateConfiguration,1.0>
	does not exist at the PowerShell module path nor is it registered as a WMI DSC resource."

Running **Get-DscResource MSFT_RoleResource** give me the following output:

	ImplementedAs   Name                      ModuleName                     Version
	-------------   ----                      ----------                     -------
	PowerShell      WindowsFeature            PSDesiredStateConfiguration    1.1


However if I copy the folder *'C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration'* from my Server 2016 VM to *'C:\Program Files\WindowsPowerShell\Modules'* at my Server 2012R2 Hyper-V Host. This results in the mof being generated looks like this:

	ResourceID = "[WindowsFeature]ADDomainServices";
	 IncludeAllSubFeature = True;
	 Ensure = "Present";
	 SourceInfo = "D:\\TestLab\\Scripts\\ModuleVersiontTests\\LabConfig.ps1::93::13::WindowsFeature";
	 Name = "AD-Domain-Services";
	 ModuleName = "PsDesiredStateConfiguration";
	 ModuleVersion = "0.0";
	
	DependsOn = {
	
	    "[xComputer]Server2016TP3"};
	
	 ConfigurationName = "LabConfig";
	
	};

This seems to work on both Server 2012R2 and Server 2016.

**Comment by iainbrighton** [comment]
Strange! Is that __Get-DscResource MSFT_RoleResource__ output from your upgraded 2012R2 host? If so, why does it still show ModuleVersion `1.0` in the generated MOF when ModuleVersion `1.1` is on the host?

My gut feeling is that, until WMF 5 is officially released down-level, we don't really know what's going to be in the box, or not. What are everybody else's thoughts on this? More testing is definately required!

**Comment by iainbrighton** [comment]
OK - I can't recreate this (at least with 2016 TP4). Here's what I've done..

Created a simple configuration on 2012R2
```
configuration WMF4 {
    Import-DscResource -Module PSDesiredStateConfiguration;
    node localhost {
        WindowsFeature AD {
            Name = 'AD-Domain-Services';
            IncludeAllSubFeature = $true;
        }
    }
}

WMF4 -OutputPath C:\
```
This generates the following MOF
```
/*
@TargetNode='localhost'
@GeneratedBy=Administrator
@GenerationDate=11/26/2015 12:07:51
@GenerationHost=2012R2
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]AD";
 IncludeAllSubFeature = True;
 SourceInfo = "::4::9::WindowsFeature";
 Name = "AD-Domain-Services";
 ModuleName = "PSDesiredStateConfiguration";
 ModuleVersion = "1.0";

};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="Administrator";
 GenerationDate="11/26/2015 12:07:51";
 GenerationHost="2012R2";
};
```
Copied the MOF to a 2016 TP4 VM and manually ran it:
```
PS C:\Users\Administrator> Start-DscConfiguration -Path C:\ -Wait -Force -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer 2016TP4 with user sid S-1-5-21-1483133696-3103038369-2041895684-500.
VERBOSE: [2016TP4]: LCM:  [ Start  Set      ]
VERBOSE: [2016TP4]: LCM:  [ Start  Resource ]  [[WindowsFeature]AD]
VERBOSE: [2016TP4]: LCM:  [ Start  Test     ]  [[WindowsFeature]AD]
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] The operation 'Get-WindowsFeature' started:
AD-Domain-Services
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] The operation 'Get-WindowsFeature' succeeded:
AD-Domain-Services
VERBOSE: [2016TP4]: LCM:  [ End    Test     ]  [[WindowsFeature]AD]  in 0.8280 seconds.
VERBOSE: [2016TP4]: LCM:  [ Start  Set      ]  [[WindowsFeature]AD]
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] Installation started...
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] Continue with installation?
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] Prerequisite processing started...
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] Prerequisite processing succeeded.
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] Installation succeeded.
VERBOSE: [2016TP4]:                            [[WindowsFeature]AD] Successfully installed the feature
AD-Domain-Services.
VERBOSE: [2016TP4]: LCM:  [ End    Set      ]  [[WindowsFeature]AD]  in 76.3390 seconds.
VERBOSE: [2016TP4]: LCM:  [ End    Resource ]  [[WindowsFeature]AD]
VERBOSE: [2016TP4]: LCM:  [ End    Set      ]
VERBOSE: [2016TP4]: LCM:  [ End    Set      ]    in  77.7920 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 83.256 seconds

PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.0
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
If I generate the same MOF on 2016 TP4 I get this:
```
/*
@TargetNode='localhost'
@GeneratedBy=Administrator
@GenerationDate=11/26/2015 13:18:27
@GenerationHost=2016TP4
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]AD";
 IncludeAllSubFeature = True;
 SourceInfo = "::4::9::WindowsFeature";
 Name = "AD-Domain-Services";
 ModuleName = "PSDesiredStateConfiguration";

ModuleVersion = "1.0";

 ConfigurationName = "WMF5";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="Administrator";
 

                        GenerationDate="11/26/2015 13:18:27";
 

                        GenerationHost="2016TP4";
 

                        Name="WMF5";


                    };
```
I can successfully take the WMF 5 generated MOF and apply it on 2012R2 too!:
```
PS C:\Users\Administrator> Start-DscConfiguration -Path C:\ -Wait -Force -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer 2012R2 with user sid S-1-5-21-3045310532-670819299-1745118827-500.
VERBOSE: [2012R2]: LCM:  [ Start  Set      ]
VERBOSE: [2012R2]: LCM:  [ Start  Resource ]  [[WindowsFeature]AD]
VERBOSE: [2012R2]: LCM:  [ Start  Test     ]  [[WindowsFeature]AD]
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] The operation 'Get-WindowsFeature' started:
AD-Domain-Services
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] The operation 'Get-WindowsFeature' succeeded:
AD-Domain-Services
VERBOSE: [2012R2]: LCM:  [ End    Test     ]  [[WindowsFeature]AD]  in 0.7970 seconds.
VERBOSE: [2012R2]: LCM:  [ Start  Set      ]  [[WindowsFeature]AD]
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] Installation started...
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] Continue with installation?
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] Prerequisite processing started...
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] Prerequisite processing succeeded.
WARNING: [2012R2]:                            [[WindowsFeature]AD] Windows automatic updating is not enabled. To ensure
 that your newly-installed role or feature is automatically updated, turn on Windows Update.
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] Installation succeeded.
VERBOSE: [2012R2]:                            [[WindowsFeature]AD] successfully installed the feature
AD-Domain-Services
VERBOSE: [2012R2]: LCM:  [ End    Set      ]  [[WindowsFeature]AD]  in 19.9770 seconds.
VERBOSE: [2012R2]: LCM:  [ End    Resource ]  [[WindowsFeature]AD]
VERBOSE: [2012R2]: LCM:  [ End    Set      ]    in  29.8095 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 21.345 seconds

PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
It looks like you've got a wonky module installed somewhere/somehow? Can you try with the latest VirtualEngineLab module and 2016 TP4 and see if you get the same behaviour?

In the interim, I'm going to try a fully patched 2012 R2 VM..

**Comment by SimonWahlin** [comment]
I still get the same behavior in TP3 but it seems to be fixed in 2016 TP4.
We can close this issue since it is fixed in TP4.

**Comment by iainbrighton** [comment]
How on earth did you manage to create and test in a lab environment so quickly?! :stuck_out_tongue_closed_eyes: 

If I find time, I'll try TP3 but I guess there was some wonky WMF 5 install/version in TP3? Thanks for clarifying.

**Comment by SimonWahlin** [comment]
I had a config already set up, took just a minute to add TP4 media to JSON and fire it off. Thats the beauty of this module!

-----Original Message-----

**Comment by iainbrighton** [comment]
@SimonWahlin FYI - there was a `Register-LabMedia` cmdlet added recently to stop you having to edit the JSON file directly and it will also persist custom settings between module updates :)

**Comment by SimonWahlin** [comment]
Nice! I'll have to check that out :)

-----Original Message-----
