### ISSUE TITLE
Support WIM files

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lab#27]
Related to discussions in issue #9, it would be great to be able to support custom WIM files.

**Comment by iainbrighton** [comment]
@csandfeld This should be implemented in v0.8.6. You can now set the `MediaType` to `WIM` and if you wanted to override the built-in media you can use `Register-LabMedia` using the same IDs.

_The media's CustomData.WindowsOptionalFeature is not currently supported. I think we should be able to enable this? Obviously the '\sources\sxs' folder is not avavilable, but if the binary files are in the WIM then this should still work?_

**Comment by csandfeld** [comment]
Thanks .. will test that as well

**Comment by csandfeld** [comment]
Have successfully tested with a WIM file - good job

**Comment by iainbrighton** [comment]
@csandfeld Do you have any thoughts on enabling the CustomData.WindowsOptionalFeature support for WIM files? Obviously this will only work for features that are 'available' in the WIM file? Seems a shame to turn it off to avoid (people would obviously need to know what they're doing)?

**Comment by csandfeld** [comment]
I would say leave it on for now, and see if any issues are logged. Assuming that documentation is on the agenda when we are nearing publishing to the gallery, I would say that this is something we could document our way out of.

**Comment by iainbrighton** [comment]
I’m on a documentation update tonight :(
