### ISSUE TITLE
Add 'Quick VM' functionality

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lab#29]
It seems a waste having to create a ConfigurationData document if you want to quickly just create a VM!

I'm thinking that we could expose the NewLabVM function as `New-LabVM` and have all the standard options supported in the ConfigurationData document available. This could then create it's own hashtable with a single 'node' in it? It would pull the default settings from `Get-LabVMDefaults`.

Something like this:
```
New-LabVM -Name <String> -MediaId <String> [[-SwitchName] <String>] [-Credential <PSCredential>] [-NoSnapshot]

New-LabVM -Name <String> -MediaId <String> [[-SwitchName] <String>] -Password <SecureString> [-NoSnapshot]
```
We could also expose the `Set-LabVMdefaults` settings, i.e. `[[-StartupMemory] <Int64>]` etc.

**Comment by csandfeld** [comment]
That is an excellent idea

**Comment by iainbrighton** [comment]
There's an initial `New-LabQuickVM` implementation here: https://github.com/VirtualEngine/Lab/commits/Issue29. Is it worth implementing all the `LabVMDefaults` values, i.e. `-MinimumMemory` and `-ProcessorCount` etc too?

_Note: there is a dynamic -Id parameter that returns all the available/registered media!_

**Comment by csandfeld** [comment]
Yes, I think it would make sense to have those values available as parameters.

**Comment by iainbrighton** [comment]
@csandfeld I knew you'd say that (and I kinda thought that myself anyway)! I shall get busy...

**Comment by csandfeld** [comment]
:)
