### ISSUE TITLE
Remove-LabConfiguration is slow (when "redo" files are large)

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lab#31]
When a VM has a snapshot, and you run Remove-LabConfiguration, it may take a long time to complete, as the command triggers a snapshot removal, that will commit all the changes stored in the "redo" file, to be commited to the VM's disk before deleting the disk.

I have not tested this yeat, but it would seem that reverting to the oldest snapshot first, and then deleting the different snapshot/redo files, and subsequently deleting the VM, would speed things up.

Let me know if this is something you would like to persue, and I will be happy to try to create a fix for it.

**Comment by iainbrighton** [comment]
Haha – I wondered how long it would take for this to crop up! This is the reason why I introduced the `–NoSnapshot` parameter on the Start-LabConfiguration and Reset-LabVM cmdlets. And that’s probably why I’d pretty-much forgotten about it..

What we could do with is working out is:

* Is there a reliable way to wait for the snapshot coercion process to finish?
* Is there a quicker way of removing an existing snapshot chain (as you've highlighted)?
* Should we not create a baseline snapshot by default
 * Add a global default
 * You can always just use Start-LabConfiguration -Force to recreate (it does recreate the VHDs though)
 * You can use Reset-LabVM to revert a single VM

I'm happy for you to investigate the available options! Thoughts?

**Comment by csandfeld** [comment]
I have made a suggested fix for this issue in the Issue31 branch of my fork:
https://github.com/csandfeld/Lab/tree/Issue31

Basicly I am Restoring the the oldest snapshot, and then deleting snapshots in the order of newest first. All in an attempt to ensure, that we do not have to commit data to the VM disk file (or another snapshot).

Let me know what you think

**Comment by iainbrighton** [comment]
@csandfeld Looks good to me. Do you know if there's a way to wait until the snapshots are actually merged? Is there a background job that's created?

**Comment by csandfeld** [comment]
Sorry for the late reply, I have been away for a few days.
I do not know of a way to wait for the snapshot merging, but there is hardly any merging going on with the approach I have suggested, as changes are discarded instead (no need to keep them, as we are deleting the VM).

If you're OK with that, I'll go ahead and create a PR.
