### ISSUE TITLE
HostDefaults.Json Issue

### ISSUE THREAD

**Issue by DexterPOSH** [VirtualEngine/Lab#33]
The HostDefaults.json uses entries like below :
>   "ConfigurationPath": "%SYSTEMDRIVE%\\TestLab\\Configurations",

I was under the impression that when I run Start-LabHostConfiguration for the first time it will automatically create the required folders under the system drive. But the %SYSTEMDRIVE% is not being expanded in the path by the function.

This creates the directory in my current path rather than the System Drive.
![labissue1](https://cloud.githubusercontent.com/assets/6275375/11528970/f7f7d00a-990f-11e5-9f42-ca61ceb627ea.png)

I can work on fixing it, if you confirm I am not doing it wrong.

**Comment by iainbrighton** [comment]
Hi @DexterPOSH - that could well be a bug. It used to create the folders when running `Set-LabHostDefaults`, but that behaviour was changed.

Looking at the screenshots, it looks like there needs to be a `ResolvePathEx -Path $property` call just before the `NewDirectory` call to expand/resolve the path first. The `Test-LabHostConfiguration` method will probably need to be fixed too!

If you're happy to fix and sent a PR that'd be appreciated!

**Comment by DexterPOSH** [comment]
Thanks @iainbrighton .
Fixing it now and will send a PR.

**Comment by DexterPOSH** [comment]
PR Created for the above bug.
https://github.com/VirtualEngine/Lab/pull/34
