### ISSUE TITLE
Rename Module

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lab#42]
I still want to rename the module to something more 'memorable'. This will also permit the module name in GitHub to reflect the actual module name (handy when downloading the .zip file!).

The ideas I have are as follows:

* __ConfLab__
 * Short for CONFigure LAB
 * It's a short and is similar to a lot of recent OSS projects
 * Google doesn't return much when searching for 'Powershell Conflab'
* __PSLab__
 * It's short
 * Sounds like 'Slab' when pronounced
 * There are one or two other 'projects' with this name
* __Bunsen__
 * The mad scientist from The Muppets
 * Quite a few 'Bunsen' projects on GitHub
 * Could be confused with 'Bunsen Labs'?
* __Beeker__
 * Derived from Beaker the lab assistant in The Muppets
 * Lots of 'Beaker' projects for configuring labs, including Puppet

Does anyone have any preferences or other ideas? I would like to get this nailed-down before publishing beta-v0.9 to the PowerShell Gallery...

**Comment by csandfeld** [comment]
- **Labster**
  - Name inspired by Pester
  - Not that many hits on Google when searching for "powershell labster"
  - May conflict with labster.com providing online science labs

**Comment by csandfeld** [comment]
- **Labrador**
  - May conflict with some Microsoft stuff on Azure - not sure what that is though (https://msdn.microsoft.com/en-us/library/azure/a3377668(v=vs.80))

**Comment by csandfeld** [comment]
- **Labtitude**
  - A play on the word aptitude (bear with me, I'm not a native english speaker, so might not make sense at all)

**Comment by csandfeld** [comment]
- **Lability**
  - Concatenating Lab and Ability, as in the ability to create a lab
  - According to wikipedia Lability also *"refers to something that is constantly undergoing change or something that is likely to undergo change"* which I would expect a lab to do

**Comment by csandfeld** [comment]
Looking furhter at the descriptions on that wiki page (https://en.wikipedia.org/wiki/Lability) I actually quite like Lability as a candidate

**Comment by iainbrighton** [comment]
Oooh - I quite like __Lability__ too and it has no match in Github! Let me see if I can drum up some other interest! Are you on Twitter? I can't seem to find you! :eyes:

**Comment by csandfeld** [comment]
Glad you like it :smile: 

Am on Twitter, same name as here @csandfeld (this is also where I originally proposed Beaker). May be a long responsetime though... not monitoring it as actively as I should.

**Comment by DexterPOSH** [comment]
+1 for **Lability** :smile:

**Comment by sqlchow** [comment]
SimuLab or BASIL(Build And Simulate Infrastructure Labs)

**Comment by csandfeld** [comment]
Excellent choice :smile:
