### ISSUE TITLE
Permit addition of custom media

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lab#9]
Add the ability to add custom media that doesn't need to be specified in the NonNodeData.VirtualEngineLab.Media array

**Comment by iainbrighton** [comment]
Being able to bring your own VHD(X)s would make using SYSPREP'd images a simple process. It should also support using VL ISO media to create images.

This will probably need be implemented with new `Register-LabImage, Unregister-LabImage, Register-LabMedia` and `Unregister-LabMedia` cmdlets. When adding an existing VHD(X) we would create a corresponding "skeleton" Media object that bypasses all the ISO expansion stuff!

**Comment by csandfeld** [comment]
Might it be possible to also support Wim files as source media? (we have custom Wim images with updates pre-applied)

**Comment by iainbrighton** [comment]
Yes - supporting Wim files should be relatively straight-forward. Do you have any specific requests?

**Comment by csandfeld** [comment]
Sounds good. As for specific requests, nothing set in stone. Am wondering though, if when media is on a local network, it might not be necessary to copy it to a local drive before creating the VHDX (however that might be overcomplicating things)

**Comment by iainbrighton** [comment]
For ISO and WIM files, I guess they could reside on a file server without having to copy them locally first. This may have a performance impact during the initial master image creation process, but this should be a one-time hit..

**Comment by csandfeld** [comment]
That was my thought as well, and would save a few gigs by not having to copy to local. On the other hand, having the media cached localy is a good thing when you are out and about.
Maybe  a config parameter could specify if media from local servers should be cached or not.

**Comment by iainbrighton** [comment]
Agreed. Should this be a global setting, I.e. On set-LabHostDefaults? You could turn caching off on a desktop if the file server should always be available. I don't see a need for turning it on/off for individual media, but that's just my use case!

**Comment by iainbrighton** [comment]
Quick question on the WIM media - do you/can you have more than 1 image in a custom WIM? I presume so, but never tried it when creating my on WIM.

**Comment by csandfeld** [comment]
A global setting would do the trick I think. Having a setting for individual media would just cause confusion and administrative overhead.

Media from the internet should of course still be cached.

**Comment by csandfeld** [comment]
Regarding WIM media, I'm quite sure you can (as is already the case with the MS install.wim's), but we don't in our wim's. Just 1 image in each.

I think it would make sense to treat the WIM's the same way as the ISO's. Point to a WIM, and specify the name of the image you want. That should keep us out of trouble with WIM's containing multiple images. Of course you could argue that if the WIM only has 1 image, there would be no need to specify the name (would support pointing to a WIM file, containing a timestamp or similar in the image name). In that case we would need to detect the number of images in the WIM, and require an image name if more than 1.

**Comment by iainbrighton** [comment]
Do we assume that any http/https Uri is on the Internet? Theoretically it could be hosted on an internal web server. That's probably over complicating things unnecessarily though!

**Comment by csandfeld** [comment]
I think that would be a fair assumption. I guess theoretically one could check a URL against Internet Explorers security zones or something like that, but I agree that it would be over complicating things.

**Comment by iainbrighton** [comment]
OK - there are 3 issues in this thread. I'll leave this issue for the support of custom media and open new threads; one for supporting custom WIM files and one for disabling the caching of ISO (and WIM) files!

**Comment by iainbrighton** [comment]
Custom media should now be supported with the `Register-LabMedia` and `Unregister-LabMedia` cmdlets in v0.8.5.

__Note: whilst WIM media can be registered in this release, it won't be supported until a commit that targets #27 is implemented.__
